Governor voting grab god token
hashgraph/hedera-accelerator-defi-dex pull request #183
Opened 2023-01-16 12:09 UTC by abhishek-k-sharma-lab49

Grab all GOD tokens when the user vote for the proposal.

2023-01-16 13:23 UTC, shivamgarglab49 commented on contracts/governance/GODHolder.sol
> +            int64(uint64(amount))
here we can use int256(amount) ?

2023-01-16 13:24 UTC, amandeeprehal-lab49 commented on contracts/governance/GovernorCountingSimpleInternal.sol
>          voters.push(voter);
Do you still need this?

2023-01-16 14:17 UTC, shivamgarglab49 commented on integrationTest/governance/GovernorMethods.ts
> +    const votingPeriod = 10; //Blocks to mint
let it be 100 .

2023-01-17 07:58 UTC, amandeeprehal-lab49 commented on integrationTest/governance/governor.ts
> +        .addAddress(treasureId.toSolidityAddress())
Why do you need this?

2023-01-17 07:58 UTC, amandeeprehal-lab49 commented on contracts/mock/ERC20Mock.sol
> +    bool needExact = false;
Pls remove this and implement what we discussed.

2023-01-23 05:54 UTC, amandeeprehal-lab49 commented on contracts/governance/GODHolder.sol
> +            revert("GODHolder: token transfer failed to contract.");
Pls change it to require in. one line.

2023-01-23 05:55 UTC, amandeeprehal-lab49 commented on contracts/governance/GODHolder.sol
> +contract GODHolder is IGODHolder, Initializable {
Pls write separate unit tests for this.

2023-01-23 06:02 UTC, amandeeprehal-lab49 requested changes

2023-01-23 06:02 UTC, amandeeprehal-lab49 commented on contracts/governance/GODHolder.sol
> +        bool isAddOperation
https://thixalongmy.haugiang.gov.vn/media/1175/clean_code.pdf 

Go to page 41

2023-01-23 06:31 UTC, amandeeprehal-lab49 commented on contracts/governance/GODHolder.sol
> +                index = i;
You can break the loop once element is found.

2023-01-23 06:42 UTC, amandeeprehal-lab49 commented on contracts/governance/GovernorCountingSimpleInternal.sol
> +        godHolder.removeActiveProposals(voters, proposalId);
How about putting this call in cleanup function itself?

`godHolder.removeActiveProposals(voters, proposalId);`

2023-01-23 06:43 UTC, amandeeprehal-lab49 commented on contracts/governance/GovernorCountingSimpleInternal.sol
> +        godHolder.removeActiveProposals(voters, proposalId);
Its getting executed from execute and cancel.

2023-01-23 07:32 UTC, amandeeprehal-lab49 commented on test/god-holder-test.ts
> +describe("Governor Tests", function () {
Change names

2023-01-23 07:32 UTC, amandeeprehal-lab49 commented on test/god-holder-test.ts
> +  describe("GovernorCountingSimpleInternal Upgradeable", function () {
Same

2023-01-23 07:36 UTC, amandeeprehal-lab49 commented on test/god-holder-test.ts
> +  it("Verify GODHolder grabtoken revert", async function () {
pls add positive cases as well.

2023-01-23 07:37 UTC, amandeeprehal-lab49 commented on test/god-holder-test.ts
> +  });
Also, test for this `removeActiveProposals`

2023-01-23 07:38 UTC, amandeeprehal-lab49 commented on test/god-holder-test.ts
> +  });
Idea should be to cover all external functions but when if they really simple you can skip them.

2023-01-23 08:41 UTC, amandeeprehal-lab49 approved these changes

2023-01-23 08:56 UTC, merged