initial changes done
hashgraph/hedera-accelerator-defi-dex pull request #387
Opened 2023-03-27 13:32 UTC by shivamgarglab49

2023-04-04 05:54 UTC, amandeeprehal-lab49 commented on contracts/dao/MultisigDAO.sol
> +    struct TranscationInfo {
Typo -  TranscationInfo -> TransactionInfo

2023-04-04 10:03 UTC, amandeeprehal-lab49 requested changes

2023-04-04 10:03 UTC, amandeeprehal-lab49 commented on contracts/gnosis/HederaGnosisSafe.sol
> +        require(checkSignatures(txHash), "Owner has not approved yet");
pls add some comments here as well to explain why we extended function. 

The cost of on-chain approval is really cheap hence we there is no need of off-chain approval.  Also, Hashpack or equivalents wallets do not support ECDSA keys.

2023-04-04 10:03 UTC, amandeeprehal-lab49 commented on contracts/mock/MockBaseHTSWithTokenCreationFail.sol
> +    ) public override returns (int256 responseCode) {}
we don't need these changes right?

2023-04-04 10:32 UTC, shivamgarglab49 commented on contracts/common/BaseHTS.sol
> +    ) public override returns (int256) {
yes, inside HederaGnosisSafe.

2023-04-04 10:34 UTC, shivamgarglab49 commented on contracts/gnosis/HederaGnosisSafe.sol
> +        return super.transferToken(token, receiver, amount);
require already there.

2023-04-11 11:20 UTC, amandeeprehal-lab49 approved these changes

2023-04-11 12:07 UTC, merged