Recommended pair for swap
hashgraph/hedera-accelerator-defi-dex pull request #407
Opened 2023-04-04 10:54 UTC by amandeeprehal-lab49

Recommended pair for swap

2023-04-04 10:57 UTC, abhishek-k-sharma-lab49 commented on contracts/Factory.sol
> +import "hardhat/console.sol";
we can remove import "hardhat/console.sol";

2023-04-04 12:15 UTC, shivamgarglab49 requested changes

2023-04-05 06:33 UTC, amandeeprehal-lab49 commented on contracts/Factory.sol
> +        return findMaxQtyPool(recommendedPairs);
You are right, let me fix.

2023-04-05 07:52 UTC, amandeeprehal-lab49 commented on contracts/Factory.sol
> +                    _token0,
Done

2023-04-05 07:56 UTC, amandeeprehal-lab49 commented on e2e-test/business/Factory.ts
> +        .addAddress(csDev.getContract(csDev.configuration).address);
Done

2023-04-05 07:56 UTC, amandeeprehal-lab49 commented on contracts/Factory.sol
> +import "hardhat/console.sol";
Removed

2023-04-05 13:11 UTC, amandeeprehal-lab49 commented on contracts/Factory.sol
> +        Configuration _configuration
Configuration is a configuration, its fine if we are directly dependent on it. If we mock it, we will create exactly same mock that why I didn't mock. Basically its kind of global state, without any behaviour.

2023-04-06 04:05 UTC, shivamgarglab49 approved these changes

2023-04-06 13:21 UTC, merged