Governor contract deduct god
hashgraph/hedera-accelerator-defi-dex pull request #46
Opened 2022-11-16 12:35 UTC by abhishek-k-sharma-lab49

Deduction of 1 GOD token on proposal creation and return it back on Execution or Cancel of the proposal complete.

2022-11-16 12:47 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        bytes32 descriptionHash = keccak256(bytes(description));
Any other terminal state? Expired ?

2022-11-16 13:53 UTC, abhishek-k-sharma-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        bytes32 descriptionHash = keccak256(bytes(description));
There are only 2 exit states for proposals, canceled or executed.

2022-11-17 09:52 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        proposalId = hashProposal(targets, values, calldatas, keccak256(bytes(description)));
you can pass descriptionHash directly. No need to calculate again - keccak256(bytes(description))

2022-11-17 09:53 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        require(msg.sender == proposalCreators[proposalId], "UnAuthorised access");
Pls add descriptive message, it will help in debugging and unit test.

2022-11-17 09:55 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +    function cancelProposal(
Pls add unit tests as well.

2022-11-17 09:57 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorTextProposal.sol
>          address[] memory,
Pls move this to abstract class.

`function _execute(
        uint256 proposalId, /* proposalId */
        address[] memory,
        uint256[] memory,
        bytes[] memory,
        bytes32 /*descriptionHash*/
    ) internal virtual override {
        returnGODToken(proposalId);
    }`

then override in subclasses using that there is no need to repeat `returnGODToken(proposalId);` in all subclasses just call super._execute

2022-11-21 10:05 UTC, abhishek-k-sharma-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        require(msg.sender == proposalCreators[proposalId], "UnAuthorised access");
done

2022-11-21 10:26 UTC, amandeeprehal-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        require(msg.sender == proposalCreators[proposalId], "UnAuthorised access");
Its still the same -

`UnAuthorised access`

2022-11-21 10:32 UTC, amandeeprehal-lab49 commented on test/governer-test.ts
> +  // const governorGenericInterface = new ethers.utils.Interface(governorGenericJson.abi);
you can remove this pls

2022-11-22 06:06 UTC, amandeeprehal-lab49 requested changes

2022-11-22 06:11 UTC, abhishek-k-sharma-lab49 commented on contracts/common/GovernorCountingSimpleInternal.sol
> +        require(msg.sender == proposalCreators[proposalId], "UnAuthorised access");
done

2022-11-22 06:12 UTC, abhishek-k-sharma-lab49 commented on test/governer-test.ts
> +    it("Execute ", async function () {
Done

2022-11-22 06:14 UTC, abhishek-k-sharma-lab49 commented on test/governer-test.ts
> +      const thrashhold = await instance.proposalThreshold();
done

2022-11-22 06:40 UTC, amandeeprehal-lab49 approved these changes

2022-11-22 06:57 UTC, amandeeprehal-lab49 approved these changes

2022-11-22 06:59 UTC, amandeeprehal-lab49 approved these changes

2022-11-22 07:37 UTC, merged